spring:
  jackson:
    time-zone: America/Argentina/Buenos_Aires
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/alkemy
    username: root
    password:
    driver:
      class: com.mysql.jdbc.Driver
app:
  sendgrid:
    key:
    templateId: 